export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST';

export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';

export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL';

export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';

export const FETCH_PRODUCT_BY_ID_FAIL = 'FETCH_PRODUCT_BY_ID_FAIL';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';